window.__SHOWS__ = [
  {
    "id": "mpjv5d7xs5jn",
    "title": "🔝家业 杨紫",
    "quality": "HD4K",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1uNHnXwNbss2w7jSTgHWmiA",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/468771b6832f",
    "isNew": true,
    "updatedDate": "2026/5/27",
    "isPinned": true,
    "isCompleted": false
  },
  {
    "id": "mpjy58agcvib",
    "title": "主角 刘浩存",
    "quality": "HD4K",
    "episode": "",
    "bdLink": "https://pan.baidu.com/s/1m1dbr3FINQh73kSOx4XAyw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/f083530afbe3",
    "isNew": true,
    "isPinned": true,
    "isCompleted": false,
    "updatedDate": "2026/5/27"
  },
  {
    "id": "mpjv5d7x1u4g",
    "title": "🔝良陈美锦",
    "quality": "HD4K",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/1Tpq-ajrTouhQsY0gmsxCzg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/9bcd15f679b7",
    "isNew": true,
    "updatedDate": "2026/5/24",
    "isPinned": true,
    "isCompleted": true
  },
  {
    "id": "mpjv5d7yke90",
    "title": "🔝大唐迷雾 冯绍峰 第一季",
    "quality": "HD4K",
    "episode": "13",
    "bdLink": "https://pan.baidu.com/s/1C2x8U4-nfsESh6IK0ER25Q",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/5ff4ec64d887",
    "isNew": true,
    "updatedDate": "2026/5/27",
    "isPinned": true,
    "isCompleted": false
  },
  {
    "id": "mpjv5d7xrb5l",
    "title": "🔝绯色潮汐",
    "quality": "1080P",
    "episode": "12",
    "bdLink": "https://pan.baidu.com/s/1edIBT3-hlse1I-ABdi3o9g",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/1b9f39887912",
    "isNew": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjv5d7yjvoz",
    "title": "🔥赌金",
    "quality": "1080P",
    "episode": "10",
    "bdLink": "https://pan.baidu.com/s/1k88Tkf6AxRwZB7uGZdxJrw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/3347293101cf",
    "isNew": true,
    "isCompleted": true,
    "updatedDate": "2026/5/27"
  },
  {
    "id": "mpjv5d7x67a1",
    "title": "香港探秘地图",
    "quality": "HD4K",
    "episode": "06",
    "bdLink": "https://pan.baidu.com/s/1GwnRCD-5lsMtFMNnGPa7gA",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/532b5e8c9d9b",
    "isNew": true,
    "updatedDate": "2026/5/26",
    "isPinned": false,
    "isCompleted": false
  },
  {
    "id": "mpjyjz5d0m3c",
    "title": "🔝八千里路云和月",
    "quality": "1080P",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/15p_CbSXgfeSm-BgUX7aRVg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/76f3184ecbca",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa1v44",
    "title": "🔝冰湖重生",
    "quality": "1080P",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/119maX-N5GF2TOYIllnG3nw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5d37hc",
    "title": "🔝成何体统",
    "quality": "1080P",
    "episode": "32",
    "bdLink": "https://pan.baidu.com/s/16VZNtbvaMvuvU-q8Cjh_og?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/8359a4e4c38d",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobc5sg",
    "title": "🔝除恶",
    "quality": "1080P",
    "episode": "16",
    "bdLink": "https://pan.baidu.com/s/1aWeDQADYtUfOEAFH867zOg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/36cb1b699d1b",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobaaej",
    "title": "🔝冬去春来",
    "quality": "HD4K",
    "episode": "32",
    "bdLink": "https://pan.baidu.com/s/1uMozisgw4E5N3m43V2eJdg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa38hv",
    "title": "🔝方圆八百里",
    "quality": "4K",
    "episode": "20",
    "bdLink": "https://pan.baidu.com/s/18RjMq6kdNGhY33JS9Y_MTw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/192282e93577",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoabmoo",
    "title": "🔝黑夜告白",
    "quality": "HD4K",
    "episode": "28",
    "bdLink": "https://pan.baidu.com/s/1dHrKS7JYbgtIeNCoc3vifg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/6c6a20d9b089",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoakq50",
    "title": "🔝佳偶天成",
    "quality": "1080P",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/1seJb9PDhOlHhImI1gjrS-Q?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dzcly",
    "title": "🔝家事法庭",
    "quality": "HD4K",
    "episode": "26",
    "bdLink": "https://pan.baidu.com/s/1-fVdIQeeXlS8iKfMzjrFlQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/2585fd1a2240",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5cbyjh",
    "title": "🔝剑来2&剑来 第二季",
    "quality": "HD4K",
    "episode": "27",
    "bdLink": "https://pan.baidu.com/s/1F1pVIYBmQCn5qyRlcrZWBw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/6cc1c7a203dd",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa6uqq",
    "title": "金关",
    "quality": "HD4K",
    "episode": "22",
    "bdLink": "",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/d491e0936e73",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5d6mup",
    "title": "🔝玫瑰丛生",
    "quality": "1080P",
    "episode": "26",
    "bdLink": "https://pan.baidu.com/s/1WxwjSZkBK0A3AzXaFAnTfw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/2553409bfd60",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5du0s6",
    "title": "🔝你好1983",
    "quality": "HD4K",
    "episode": "36",
    "bdLink": "https://pan.baidu.com/s/1LpmKEzjUHlEPdqonWk_HMw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/4fd39b8975b6",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5da2yc",
    "title": "🔝你是迟来的欢喜",
    "quality": "1080P",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/11g4H5LDocMAnA0a5zAkvuQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/e4252dbc1b50",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmockzdb",
    "title": "🔝年少有为",
    "quality": "HD4K",
    "episode": "26",
    "bdLink": "https://pan.baidu.com/s/1dpXjwRoIwCvzmXwto6N_gA?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/34846dacdfb0",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoculwp",
    "title": "🔝女神蒙上眼",
    "quality": "HD4K",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/1dXjefss3WC4pxXlf1ZpiLg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmob4jkj",
    "title": "🔝叵测",
    "quality": "1080P",
    "episode": "16",
    "bdLink": "https://pan.baidu.com/s/1zATN087PEvhI-tcs312iFQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/0d68c6107d14",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa7u2u",
    "title": "🔝人间惊鸿客",
    "quality": "HD4K",
    "episode": "22",
    "bdLink": "https://pan.baidu.com/s/19AcWUyX8pXn6ReYj3_L4cQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/b9d255bb5a81",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dog20",
    "title": "🔝生命树",
    "quality": "HD4K",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/1iOoV6PeFwWXt053itRXY9w?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/aceaf31cb56c",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobenlo",
    "title": "🔝她的盛焰",
    "quality": "HD4K",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/1l_TSimUyMiKKCaO3O0tpTA?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/e9a82713dc1c",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5d7pzj",
    "title": "🔝太平年",
    "quality": "HD4K",
    "episode": "48",
    "bdLink": "https://pan.baidu.com/s/1GgL2xh2UILB9qYI5sPq5sg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/34846dacdfb0",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dm3pu",
    "title": "🔝唐宫奇案之青雾风鸣",
    "quality": "1080P",
    "episode": "34",
    "bdLink": "https://pan.baidu.com/s/1MgtqaRf1y0RtLrMfJf8DVA?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/938cdfb2eef5",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobganm",
    "title": "🔝危险关系",
    "quality": "HD4K",
    "episode": "22",
    "bdLink": "https://pan.baidu.com/s/1Zn3hreBpjUQlPljJELSWrg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/31f40f64384b",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoavir8",
    "title": "🔝夏末初见",
    "quality": "HD4K",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/1m76cHUYAqwGExuMdkjgqug?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/7d956b906026",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dxtew",
    "title": "🔝乡村爱情18",
    "quality": "1080P",
    "episode": "40",
    "bdLink": "https://pan.baidu.com/s/1bz2NQj4kYh-lzCjNzOztMQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobg0j7",
    "title": "🔝夜色正浓",
    "quality": "HD4K",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1wqRnF6Ng8oT5-BaiJa31BA?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dog8q",
    "title": "🔝隐身的名字",
    "quality": "HD4K",
    "episode": "31",
    "bdLink": "https://pan.baidu.com/s/1us32XWTYKXbS_Ok8i1JNYw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/32f20edb162d",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5d0t20",
    "title": "🔝有罪之身",
    "quality": "1080P",
    "episode": "14",
    "bdLink": "https://pan.baidu.com/s/1ipoG-V2X3fTzvLkn72qqcg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/737ccceb9b82",
    "isNew": true,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dk2if",
    "title": "🔝正义女神",
    "quality": "1080P",
    "episode": "25",
    "bdLink": "https://pan.baidu.com/s/1FVxFbeKGXcdQifhyTsqbwg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoainqv",
    "title": "🔝重案解密",
    "quality": "1080P",
    "episode": "12",
    "bdLink": "https://pan.baidu.com/s/1b3x8d_xgZL1HzMh5ZDIq5Q?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/8b587f1e5868",
    "isNew": true,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobcyiu",
    "title": "🔝逐玉",
    "quality": "1080P",
    "episode": "40",
    "bdLink": "",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/2d7f0e058607",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5cu8r3",
    "title": "🔥飞驰人生3 第三部",
    "quality": "1080P",
    "episode": "1",
    "bdLink": "https://pan.baidu.com/s/17RkjY8DkMLi2tXa9QW2atg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/3374735144b5",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoajgy1",
    "title": "🔥掌中刃",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1xMesxIx4WdCLNdPsf2aYKQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/0bde395caa2d",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoao2zv",
    "title": "🔥着迷",
    "quality": "1080P",
    "episode": "22",
    "bdLink": "https://pan.baidu.com/s/1W8MaR3qsJ9OhOO6dFZ9xOw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/ebd5336331d0",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa2k58",
    "title": "爱情没有神话",
    "quality": "HD4K",
    "episode": "37",
    "bdLink": "https://pan.baidu.com/s/1eXAOuMfqxlb7k1f0DzBvuw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobcaa4",
    "title": "纯真年代的爱情",
    "quality": "HD4K",
    "episode": "29",
    "bdLink": "",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/556f0832b17d",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjxsz5aln28",
    "title": "低智商犯罪",
    "quality": "4k",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/16q7MEBBFofDIxMpXnn9pUA?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/f52cbd6dab0e",
    "isNew": false,
    "updatedDate": "2026/5/24",
    "isPinned": false,
    "isCompleted": true
  },
  {
    "id": "mpjyjz5d2chr",
    "title": "繁华落尽",
    "quality": "1080P",
    "episode": "34",
    "bdLink": "https://pan.baidu.com/s/1t_LjVKyO__sHJDzpXo56BQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/133b0ceba797",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmocc37h",
    "title": "风过留痕",
    "quality": "1080P",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/1xvp93RGfY5He6wBEevgvjg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/a3e821f8dd5b",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobrzwc",
    "title": "钢铁森林",
    "quality": "1080P",
    "episode": "28",
    "bdLink": "https://pan.baidu.com/s/1Wco7Ws3YvwBIk4u5D9Hv-g?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/013ddcdf661a",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa0fda",
    "title": "憨婿",
    "quality": "1080P",
    "episode": "28",
    "bdLink": "https://pan.baidu.com/s/1lz4RvmQxhRnXoKG8T7MEwQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/652c57e3151d",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobnndq",
    "title": "江湖夜雨十年灯",
    "quality": "1080P",
    "episode": "37",
    "bdLink": "https://pan.baidu.com/s/1ZIwkMxUZC7tXnNMuFGwIjg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/30f857ae3c0f",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa6p81",
    "title": "喀什恋歌",
    "quality": "1080P",
    "episode": "08",
    "bdLink": "https://pan.baidu.com/s/1_CvkQr4eMaljC5Ikw14E4w?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/1bd631602b13",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoagsbq",
    "title": "两心不疑",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1TGVDMedhEv8DRgx53ODZkg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/386cda153bd5",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoarqme",
    "title": "蜜语纪",
    "quality": "4K",
    "episode": "38",
    "bdLink": "https://pan.baidu.com/s/16_CkDqArYiUNMPu0lQCIHg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/4ab963dc1076",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmocce92",
    "title": "十八岁太奶奶驾到，重整家族荣耀4",
    "quality": "1080P",
    "episode": "1",
    "bdLink": "https://pan.baidu.com/s/1RyyiYFE5n0HR8Ka8ccy-kg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/63b7a1d8ae0c",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyjz5dnxqg",
    "title": "岁月有情时",
    "quality": "HD4K",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/1FUczjjYap8BGkiQLRXfBTw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/92892801aabd",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoa9olx",
    "title": "她的罪名",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1hxvSijpicg3gvh9fdmqc-w?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/510009e294ce",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmoc9k30",
    "title": "唐诡奇案",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1CPbMPxsfXxqDnyvfQSitIQ?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/6c221e2b0755",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobelpw",
    "title": "我的妈妈是校花",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1mvmaCexYJ-46LCzBaf1CCw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/d9bdf5238434",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobgh5m",
    "title": "月鳞绮纪",
    "quality": "1080P",
    "episode": "29",
    "bdLink": "https://pan.baidu.com/s/1dIqF0MoZeOLkTZoHh1gIYg?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/947b7ecd2065",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpjyqmobodk4",
    "title": "遮天-剧场版 背棺战王腾",
    "quality": "4K",
    "episode": "1",
    "bdLink": "https://pan.baidu.com/s/1ZJ45J9r5f-ja6ACMgyF6Aw?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/66d67ee6b9a0",
    "isNew": false,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/24"
  },
  {
    "id": "mpl6g560qkgi",
    "title": "雨霖铃  杨洋 章若楠",
    "quality": "4k",
    "episode": "30",
    "bdLink": "https://pan.baidu.com/s/1_-gpijea-MaBVXZnQ52Tfw",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/b07b9d7c0ff1",
    "isNew": true,
    "isPinned": true,
    "isCompleted": false,
    "updatedDate": "2026/5/27"
  },
  {
    "id": "mpl6kdwzepn3",
    "title": "绯色潮汐",
    "quality": "1080P",
    "episode": "14",
    "bdLink": "https://pan.baidu.com/s/1edIBT3-hlse1I-ABdi3o9g",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/1b9f39887912",
    "isNew": true,
    "isPinned": false,
    "isCompleted": false,
    "updatedDate": "2026/5/25"
  },
  {
    "id": "mpl6liee6yy0",
    "title": "嫁金枝",
    "quality": "1080P",
    "episode": "24",
    "bdLink": "https://pan.baidu.com/s/1lngTBtR0Nbyww7M7dLX9_A?pwd=8888",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/a928400e7a49",
    "isNew": true,
    "isPinned": false,
    "isCompleted": true,
    "updatedDate": "2026/5/25"
  },
  {
    "id": "mpl6mdzqig3r",
    "title": "盛唐奇案",
    "quality": "1080P",
    "episode": "14",
    "bdLink": "https://pan.baidu.com/s/1_K9d7f_j-R9cJf_aUKdTew",
    "bdCode": "8888",
    "kkLink": "https://pan.quark.cn/s/bc670b321f99",
    "isNew": true,
    "isPinned": false,
    "isCompleted": false,
    "updatedDate": "2026/5/25"
  }
];
